### ISSUE TITLE
CUDA is required, but it's not in requirements.txt

### ISSUE THREAD

**Issue by EntityinArray** [etched-ai/open-oasis#12]
You install torch without CUDA, and require it in generate.py
this repo won't run out of the box

```
(venv) PS C:\Users\entityinarray\Projects\open-oasis> python .\generate.py
Traceback (most recent call last):
  File "C:\Users\entityinarray\Projects\open-oasis\generate.py", line 13, in <module>
    assert torch.cuda.is_available()
```

https://github.com/etched-ai/open-oasis/blob/f4563c623715239a6b0a3080dcb2405767da0b87/requirements.txt#L24
https://github.com/etched-ai/open-oasis/blob/f4563c623715239a6b0a3080dcb2405767da0b87/generate.py#L13

**Comment by julian-q** [comment]
Sorry about that! I've updated the installation instructions to explicitly require CUDA.
I think other backends should probably work as well, but for now we've only tested on CUDA. Let me know if the [new instructions](https://github.com/etched-ai/open-oasis/blob/a9d9ee7cf5da24465ab31efb46f502f5a9857f7c/README.md?plain=1#L17-L20) help?
