### ISSUE TITLE
Extensive issues with requirements.txt and generate.py

### ISSUE THREAD

**Issue by StuoodJ** [etched-ai/open-oasis#13]
First the requirments.txt dont download the correct requirements, for example the generate py script asserts to check wheter torch's version is on CUDA, although the requirements.txt does not install the CUDA version of torch, this causes a problem with the script since there isnt a correct torch, removing this assert results in the code being able to work, although the following error happens, stating i dont have the oasis500m.pt weight, even though i had already installed it. 
`  ckpt = torch.load("oasis500m.pt")
Traceback (most recent call last):
  File "generate.py", line 17, in <module>
    ckpt = torch.load("oasis500m.pt")
  File "C:\Users\every\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\serialization.py", line 1065, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "C:\Users\every\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\serialization.py", line 468, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "C:\Users\every\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\serialization.py", line 449, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'oasis500m.pt' `

I believe this is just an error with the requirments text itself, because there are numerous errors elsewhere in the file, for example av 13.1.0, i dont know if its a problem with my system being unable to install it, or a problem with pip being able to install it, because everytime its command to install it is run I get this error.

`ERROR: Ignored the following versions that require a different python version: 13.0.0 Requires-Python >=3.9; 13.1.0 Requires-Python >=3.9
ERROR: Could not find a version that satisfies the requirement av==13.1.0 (from versions: 0.1.0, 0.2.0, 0.2.1, 0.2.2, 0.2.3, 0.2.4, 0.3.0, 0.3.1, 0.3.2, 0.3.3, 0.4.0, 0.4.1, 0.5.0, 0.5.1, 0.5.2, 0.5.3, 6.0.0, 6.1.0, 6.1.2, 6.2.0, 7.0.0, 7.0.1, 8.0.0, 8.0.1, 8.0.2, 8.0.3, 8.1.0, 9.0.0, 9.0.1, 9.0.2, 9.1.0, 9.1.1, 9.2.0, 10.0.0, 11.0.0, 12.0.0, 12.1.0, 12.2.0, 12.3.0)
ERROR: No matching distribution found for av==13.1.0` 

Even though I already have python 3.9 and above installed on my system as 64bit also onto the PATH, it could just be a problem with my computer though.

**Comment by julian-q** [comment]
Thanks for your question @StuoodJ 
For pip dependencies, I updated the [installation instructions](https://github.com/etched-ai/open-oasis/blob/a9d9ee7cf5da24465ab31efb46f502f5a9857f7c/README.md?plain=1#L17-L20).
For the checkpoint files, just make sure they're in the `open-oasis` directory!
Let me know if this helps.

**Comment by StuoodJ** [comment]
Thank you for answering, the problem with the checkpoints not being there for me was a problem with my huggingface client, it didnt upload the checkpoint files to the `open-oasis` directory, which is why they didn't show up, im currently downloading the updated dependencies so I will update on it soon. Also it was a problem with pip which caused the error with the av dependency, so I have switched to Anaconda3 and it works.

**Comment by julian-q** [comment]
Glad to hear it's working!
