### ISSUE TITLE
The meaning of action vector

### ISSUE THREAD

**Issue by xizaoqu** [etched-ai/open-oasis#33]
Hi, thanks for presenting this interesting work. I notice that the action is a 25-dimension vector. Could you tell me its meaning? Thanks.

**Comment by vancyland** [comment]
hi, also confused by this, have you got a solution?

**Comment by seonjunn** [comment]
It's defined here, if these semantics are what you needed.
https://github.com/etched-ai/open-oasis/blob/f59deef2c019c212bd0c5a3a5b986a51f3701847/utils.py#L31-L57
